parameters:
    lightsaml_sp.route.discovery: lightsaml_sp.discovery
    lightsaml.route.login_check: lightsaml_sp.login_check

services:
    lightsaml_sp.username_mapper.simple:
        class: LightSaml\SpBundle\Security\User\SimpleUsernameMapper
        arguments:
            - []

    lightsaml_sp.token_factory:
        class: LightSaml\SpBundle\Security\Authentication\Token\SamlSpTokenFactory

    lightsaml_sp.slo.message_factory:
        class: LightSaml\SpBundle\Model\Protocol\LogoutMessageContextFactory
        arguments:
            - "%lightsaml.own.entity_id%"
            - "@lightsaml.party.idp_entity_descriptor_store"